
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package challenge;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ZADD = 8;
  public static final int INCR = 7;
  public static final int NUMBER = 12;
  public static final int ZCARD = 9;
  public static final int MEMBER = 14;
  public static final int SET = 3;
  public static final int EOF = 0;
  public static final int DEL = 5;
  public static final int SECONDS = 4;
  public static final int VALUE = 13;
  public static final int ZRANK = 10;
  public static final int error = 1;
  public static final int GET = 2;
  public static final int ZRANGE = 11;
  public static final int DBSIZE = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "GET",
  "SET",
  "SECONDS",
  "DEL",
  "DBSIZE",
  "INCR",
  "ZADD",
  "ZCARD",
  "ZRANK",
  "ZRANGE",
  "NUMBER",
  "VALUE",
  "MEMBER"
  };
}

